spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/renaissance_bank_demo
    password: pass
    username: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
